import re
from pathlib import Path

from psycopg.types.json import Jsonb


connect = wiz.model("db/postgres").connect
local_executor = wiz.model("struct/local_executor")
webserver = wiz.model("struct/webserver")
certificates = wiz.model("struct/service_nginx_certificates")
domains_model = wiz.model("struct/domains")
ddns_model = wiz.model("struct/domains_ddns")
config = wiz.config("docker_infra")

DOMAIN_RE = re.compile(r"^[A-Za-z0-9*.][A-Za-z0-9.*-]{0,251}[A-Za-z0-9]$")
PROXY_HOST_RE = re.compile(r"^[A-Za-z0-9_.:-]+$")


def _safe_segment(value):
    return re.sub(r"[^A-Za-z0-9_.-]+", "-", str(value or "").strip()).strip(".-") or "service"


def _read(path):
    if not path.exists():
        return None
    if path.is_symlink():
        return {"type": "symlink", "target": str(path.readlink())}
    return {"type": "file", "content": path.read_text(encoding="utf-8")}


def _restore(path, snapshot):
    if path.exists() or path.is_symlink():
        path.unlink()
    if snapshot is None:
        return
    if snapshot.get("type") == "symlink":
        path.symlink_to(snapshot.get("target"))
        return
    path.write_text(snapshot.get("content") or "", encoding="utf-8")


def _proxy_host(value):
    host = str(value or "").strip()
    if not host or PROXY_HOST_RE.match(host) is None:
        host = "127.0.0.1"
    if ":" in host and not host.startswith("[") and host.count(":") >= 2:
        return f"[{host}]"
    return host


def _proxy_location(host, port):
    upstream = f"{_proxy_host(host)}:{int(port)}"
    return f"""
    location / {{
        proxy_pass http://{upstream};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }}
""".rstrip()


def _render(domain, host, port, cert=None):
    header = "# Managed by Docker Infra. Do not edit this file directly."
    if cert:
        return f"""{header}
server {{
    listen 80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl;
    server_name {domain};
    ssl_certificate {cert["cert_path"]};
    ssl_certificate_key {cert["key_path"]};
{_proxy_location(host, port)}
}}
"""
    return f"""{header}
server {{
    listen 80;
    server_name {domain};
{_proxy_location(host, port)}
}}
"""


class ServiceNginx:
    def _paths(self, domain, env=None):
        nginx = webserver.nginx_defaults()
        available = Path(nginx.get("available_site_path") or "/etc/nginx/sites-available")
        enabled = Path(nginx.get("site_path") or "/etc/nginx/sites-enabled")
        filename = f"docker-infra-{_safe_segment(domain)}.conf"
        return nginx, available / filename, enabled / filename

    def _domain_rows(self, service_id, env=None):
        with connect(env=env) as connection:
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM services WHERE id = %s", (service_id,))
                service = cursor.fetchone()
                cursor.execute("SELECT * FROM service_domains WHERE service_id = %s ORDER BY created_at ASC", (service_id,))
                domains = [dict(row) for row in cursor.fetchall()]
        return dict(service) if service else None, domains

    def _write_domain(self, domain_row, env=None):
        domain = str(domain_row.get("domain") or "").strip().lower()
        if DOMAIN_RE.match(domain) is None:
            raise ValueError(f"{domain} 도메인 형식이 올바르지 않습니다.")
        metadata = dict(domain_row.get("metadata") or {})
        port = int(metadata.get("published_port") or domain_row.get("port") or metadata.get("target_port") or 80)
        proxy_host = metadata.get("proxy_host") or "127.0.0.1"
        cert = certificates.valid_cert(domain, zone_id=metadata.get("zone_id"), env=env)
        nginx, available_path, enabled_path = self._paths(domain, env=env)
        if nginx.get("installed") is not True:
            raise RuntimeError("nginx가 설치되어 있지 않습니다.")
        available_path.parent.mkdir(parents=True, exist_ok=True)
        enabled_path.parent.mkdir(parents=True, exist_ok=True)
        snapshot = {"available": _read(available_path), "enabled": _read(enabled_path)}
        available_path.write_text(_render(domain, proxy_host, port, cert=cert), encoding="utf-8")
        if enabled_path.exists() or enabled_path.is_symlink():
            enabled_path.unlink()
        enabled_path.symlink_to(available_path)
        return {
            "id": str(domain_row.get("id")),
            "domain": domain,
            "port": port,
            "proxy_host": _proxy_host(proxy_host),
            "ssl_mode": certificates.certificate_mode(cert),
            "available_path": str(available_path),
            "enabled_path": str(enabled_path),
            "snapshot": snapshot,
        }

    def _restore_domain(self, applied):
        available_path = Path(applied["available_path"])
        enabled_path = Path(applied["enabled_path"])
        snapshot = applied.get("snapshot") or {}
        _restore(available_path, snapshot.get("available"))
        _restore(enabled_path, snapshot.get("enabled"))

    def _mark_domains(self, applied, env=None):
        with connect(env=env) as connection:
            with connection.cursor() as cursor:
                for item in applied:
                    cursor.execute("SELECT * FROM service_domains WHERE id = %s", (item["id"],))
                    row = cursor.fetchone()
                    if row is None:
                        continue
                    metadata = dict(row["metadata"] or {})
                    metadata.update({
                        "nginx_config_path": item["available_path"],
                        "nginx_enabled_path": item["enabled_path"],
                        "nginx_ssl_mode": item["ssl_mode"],
                        "published_port": item["port"],
                        "proxy_host": item["proxy_host"],
                    })
                    cursor.execute("UPDATE service_domains SET metadata = %s, updated_at = now() WHERE id = %s", (Jsonb(metadata), row["id"]))

    def _check_and_reload(self, commands, label, env=None):
        configtest = local_executor.run("proxy.nginx.configtest", timeout_seconds=20, env=env)
        commands.append({"step": f"{label} configtest", "result": configtest})
        if configtest.get("status") != "ok":
            raise RuntimeError("nginx 설정 검사를 통과하지 못했습니다.")
        reload_result = local_executor.run("proxy.nginx.reload", timeout_seconds=20, env=env)
        commands.append({"step": f"{label} reload", "result": reload_result})
        if reload_result.get("status") != "ok":
            raise RuntimeError("nginx reload에 실패했습니다.")

    def _certbot_targets(self, domains, env=None):
        targets = []
        self_signed_test = certificates.self_signed_test_enabled(env=env)
        for row in domains:
            domain = str(row.get("domain") or "").strip().lower()
            metadata = dict(row.get("metadata") or {})
            if row.get("ssl_mode") != "certbot" and self_signed_test is not True:
                continue
            if certificates.valid_cert(domain, zone_id=metadata.get("zone_id"), env=env):
                continue
            targets.append(domain)
        return sorted(set(targets))

    def _issue_certificates(self, targets, commands, env=None):
        certificates.issue_certificates(targets, commands, env=env)

    def _ensure_dns_records(self, domains, commands, env=None):
        ensured = []
        for row in domains:
            domain = str(row.get("domain") or "").strip().lower()
            metadata = dict(row.get("metadata") or {})
            if not domain:
                continue
            if self._uses_ddns_provider(row):
                result = {"status": "skipped", "domain": domain, "reason": "ddns_managed"}
            else:
                result = domains_model.ensure_service_dns_record(
                    domain,
                    zone_config_id=metadata.get("zone_id"),
                    content=config.advertise_address(env),
                    proxied=metadata.get("dns_proxied") is True,
                    env=env,
                )
            ensured.append(result)
            commands.append({
                "step": f"dns {domain}",
                "result": {
                    "status": "ok" if result.get("status") in {"ok", "skipped"} else "error",
                    "stdout": result,
                    "stderr": "",
                    "exit_code": 0 if result.get("status") in {"ok", "skipped"} else 1,
                },
            })
        return ensured

    def _uses_ddns_provider(self, domain_row):
        metadata = dict(domain_row.get("metadata") or {})
        return metadata.get("dns_provider") == "ddns" or bool(metadata.get("ddns_endpoint_id"))

    def _ddns_domains(self, domains):
        return [row for row in domains if self._uses_ddns_provider(row)]

    def apply(self, service_id, env=None):
        service, domains = self._domain_rows(service_id, env=env)
        if not service:
            return {"status": "skipped", "message": "서비스를 찾을 수 없습니다.", "applied": []}
        if not domains:
            return {"status": "skipped", "message": "연결된 도메인이 없습니다.", "applied": []}
        nginx_domains = domains
        applied = []
        active_applied = []
        commands = []
        try:
            for domain in nginx_domains:
                applied.append(self._write_domain(domain, env=env))
            active_applied = list(applied)
            dns_records = []
            ddns_result = {"status": "skipped", "registered": [], "skipped": [], "failures": []}
            if nginx_domains:
                self._check_and_reload(commands, "nginx", env=env)
                dns_records = self._ensure_dns_records(nginx_domains, commands, env=env)
                ddns_domains = self._ddns_domains(nginx_domains)
                if ddns_domains:
                    ddns_result = ddns_model.register_service_domains(service_id, domain_rows=ddns_domains, env=env)
                    commands.append({
                        "step": "ddns register",
                        "result": {
                            "status": "ok" if ddns_result.get("status") in {"ok", "skipped"} else "error",
                            "stdout": ddns_result,
                            "stderr": "",
                            "exit_code": 0 if ddns_result.get("status") in {"ok", "skipped"} else 1,
                        },
                    })
            certbot_targets = self._certbot_targets(nginx_domains, env=env)
            if certbot_targets:
                self._issue_certificates(certbot_targets, commands, env=env)
                active_applied = []
                for domain in nginx_domains:
                    reapplied = self._write_domain(domain, env=env)
                    applied.append(reapplied)
                    active_applied.append(reapplied)
                self._check_and_reload(commands, "nginx ssl", env=env)
            self._mark_domains(active_applied, env=env)
            public_applied = [{key: value for key, value in item.items() if key != "snapshot"} for item in active_applied]
            message = "nginx 설정을 적용했습니다."
            if ddns_result.get("status") == "ok":
                message = "nginx 설정과 DDNS DNS 등록을 적용했습니다."
            return {"status": "ok", "message": message, "applied": public_applied, "dns_records": dns_records, "ddns": ddns_result, "commands": commands}
        except Exception as exc:
            for item in reversed(applied):
                self._restore_domain(item)
            rollback = {"status": "skipped", "stdout": "", "stderr": "", "exit_code": 0}
            if applied:
                rollback = local_executor.run("proxy.nginx.configtest", timeout_seconds=20, env=env)
            commands.append({"step": "nginx rollback configtest", "result": rollback})
            public_applied = [{key: value for key, value in item.items() if key != "snapshot"} for item in applied]
            return {"status": "error", "message": str(exc), "applied": public_applied, "commands": commands}


Model = ServiceNginx()
