import unittest
from pathlib import Path


ROOT = Path("/root/docker-infra/project/main")
DOMAINS_TEMPLATE = ROOT / "src" / "app" / "page.domains" / "view.pug"
DOMAINS_VIEW = ROOT / "src" / "app" / "page.domains" / "view.ts"
DOMAINS_CLOUDFLARE = ROOT / "src" / "model" / "struct" / "domains_cloudflare.py"
DOMAINS_DDNS = ROOT / "src" / "model" / "struct" / "domains_ddns.py"
LOCAL_COMMAND_CATALOG = ROOT / "src" / "model" / "struct" / "local_command_catalog.py"
LOCAL_COMMAND_SCRIPTS = ROOT / "src" / "model" / "struct" / "local_command_scripts.py"
RUNTIME_CONFIG = ROOT / "config" / "docker_infra.py"
SERVICE_NGINX = ROOT / "src" / "model" / "struct" / "service_nginx.py"
SERVICES_PREFLIGHT = ROOT / "src" / "model" / "struct" / "services_preflight.py"
SEARCH_SELECT_TEMPLATE = ROOT / "src" / "app" / "component.search.select" / "view.html"
SEARCH_SELECT_VIEW = ROOT / "src" / "app" / "component.search.select" / "view.ts"


class DomainManagementUiStaticContractTest(unittest.TestCase):
    def test_domain_records_use_compact_content_and_detail_modal(self):
        template = DOMAINS_TEMPLATE.read_text(encoding="utf-8")
        view = DOMAINS_VIEW.read_text(encoding="utf-8")

        self.assertIn("recordDetailModalOpen", template)
        self.assertIn("openRecordDetail(record)", template)
        self.assertIn("contentSummary(record)", template)
        self.assertIn("Name 또는 Content 검색", template)
        self.assertIn("query: ''", view)
        self.assertIn("filters.query", view)
        self.assertNotIn("recordFilters.name", view)
        self.assertNotIn("recordFilters.content", view)
        self.assertNotIn("Exposure", template)
        self.assertNotIn("Cloudflare Proxy 사용", template)
        self.assertNotIn("Priority", template)
        self.assertNotIn("레코드 타입 안내", template)
        self.assertNotIn("Domain 설정", template)

    def test_record_type_toggle_and_hidden_dns_defaults_are_wired(self):
        template = DOMAINS_TEMPLATE.read_text(encoding="utf-8")
        view = DOMAINS_VIEW.read_text(encoding="utf-8")
        cloudflare = DOMAINS_CLOUDFLARE.read_text(encoding="utf-8")

        self.assertIn('(click)="setRecordType(type)"', template)
        self.assertIn("recordNameHelper()", template)
        self.assertIn("DEFAULT_TTL_BY_TYPE", view)
        self.assertIn("proxied: false", view)
        self.assertIn("DEFAULT_TTL_BY_TYPE", cloudflare)
        self.assertIn("PROXIED_CAPABLE_TYPES", cloudflare)
        self.assertIn('cf_payload["proxied"] = False', cloudflare)
        self.assertIn("DEFAULT_PRIORITY_BY_TYPE", cloudflare)

    def test_certificate_service_links_open_service_detail(self):
        template = DOMAINS_TEMPLATE.read_text(encoding="utf-8")
        view = DOMAINS_VIEW.read_text(encoding="utf-8")

        self.assertIn("serviceDetailHref(item)", template)
        self.assertIn("fa-arrow-right", template)
        self.assertIn("상세", template)
        self.assertIn("/services/${this.service.encodeRouteSegment(serviceId)}", view)

    def test_ddns_management_server_is_separate_from_cloudflare_zone_flow(self):
        template = DOMAINS_TEMPLATE.read_text(encoding="utf-8")
        view = DOMAINS_VIEW.read_text(encoding="utf-8")
        api = (ROOT / "src" / "app" / "page.domains" / "api.py").read_text(encoding="utf-8")
        ddns = DOMAINS_DDNS.read_text(encoding="utf-8")
        domains = (ROOT / "src" / "model" / "struct" / "domains.py").read_text(encoding="utf-8")
        local_commands = LOCAL_COMMAND_CATALOG.read_text(encoding="utf-8")
        local_scripts = LOCAL_COMMAND_SCRIPTS.read_text(encoding="utf-8")
        runtime_config = RUNTIME_CONFIG.read_text(encoding="utf-8")
        nginx = SERVICE_NGINX.read_text(encoding="utf-8")
        preflight = SERVICES_PREFLIGHT.read_text(encoding="utf-8")

        self.assertIn("DDNS 관리 서버", template)
        self.assertIn("DDNS 서버 API", template)
        self.assertIn("/api/ddns/update", template)
        self.assertIn("*.sub.season.co.kr", template)
        self.assertIn("sub.season.co.kr만 입력하세요", template)
        self.assertIn("ddnsForm.api_url", template)
        self.assertIn("ddnsForm.token_value", template)
        self.assertIn("HTTPS 인증서 검증", template)
        self.assertIn("자체 서명/사설 인증서", template)
        self.assertIn("Dispatcher 마지막 요청", template)
        self.assertIn("endpoint.dispatcher?.last_sent_ip", template)
        self.assertIn("Dispatcher 등록", template)
        self.assertIn("ensureDdnsDispatcher()", template)
        self.assertIn("ddnsDispatcherBadgeClass()", template)
        self.assertIn("table(class=\"w-full min-w-[920px]", template)
        self.assertIn("forceUpdateDdnsEndpoint(endpoint)", template)
        self.assertIn("API 호출", template)
        self.assertNotIn("API Base URL", template)
        self.assertNotIn("등록/갱신 경로", template)
        self.assertNotIn("Health 경로", template)
        self.assertNotIn("서비스 도메인 선택에 사용", template)
        self.assertNotIn("ddnsForm.registration_path", template)
        self.assertNotIn("ddnsForm.health_path", template)
        self.assertNotIn("ddnsForm.enabled", template)
        self.assertNotIn('(click)="checkDdnsEndpoint(endpoint)"', template)
        self.assertIn("save_ddns_endpoint", api)
        self.assertIn("force_update_ddns_endpoint", api)
        self.assertIn("ensure_ddns_dispatcher", api)
        self.assertIn("ddns_unavailable", api)
        self.assertIn("api_url", view)
        self.assertIn("forceUpdateDdnsEndpoint", view)
        self.assertIn("ensureDdnsDispatcher", view)
        self.assertIn("ddnsDispatcher", view)
        self.assertIn("ddnsUpdateEndpointId", view)
        self.assertNotIn("checkDdnsEndpoint", view)
        self.assertNotIn("registration_path: endpoint.registration_path", view)
        self.assertNotIn("health_path: endpoint.health_path", view)
        self.assertNotIn("enabled: endpoint.enabled", view)
        self.assertIn("ddnsEndpoints", view)
        self.assertIn("ddnsWarning", view)
        self.assertIn("ddnsWarning()", template)
        self.assertIn("class DomainDdns", ddns)
        self.assertIn("ddns_endpoints", ddns)
        self.assertIn("ddns_registrations", ddns)
        self.assertIn("DDNS_SCHEMA_PENDING", ddns)
        self.assertIn("to_regclass('ddns_endpoints')", ddns)
        self.assertIn("def _api_endpoint", ddns)
        self.assertIn("\"api_url\"", ddns)
        self.assertIn('DEFAULT_REGISTRATION_PATH = "/api/ddns/update"', ddns)
        self.assertIn('"X-DDNS-Key"', ddns)
        self.assertNotIn('headers["Authorization"] = f"Bearer {token}"', ddns)
        self.assertIn('"hostname": domain', ddns)
        self.assertIn('"ip": target["host"]', ddns)
        self.assertIn('config.ddns_public_ip_urls', ddns)
        self.assertIn('_lookup_public_ip', ddns)
        self.assertIn('sync_dispatcher', ddns)
        self.assertIn('force_update_endpoint', ddns)
        self.assertIn('dispatcher_status', ddns)
        self.assertIn('ensure_dispatcher', ddns)
        self.assertIn('force_install', ddns)
        self.assertIn('_dispatcher_summaries', ddns)
        self.assertIn('"last_sent_at"', ddns)
        self.assertIn("ddns_management", ddns)
        self.assertIn("register_service_domains", ddns)
        self.assertIn("unregister_service_domains", ddns)
        self.assertIn("def _response_failure", ddns)
        self.assertIn("def _assert_response_ok", ddns)
        self.assertIn("PreserveMethodRedirectHandler", ddns)
        self.assertIn("_existing_registration_current", ddns)
        self.assertIn("_mark_registration_failed", ddns)
        self.assertIn("ddns.dispatcher.ensure", local_commands)
        self.assertIn("/etc/NetworkManager/dispatcher.d/90-docker-infra-ddns", local_commands)
        self.assertIn("DDNS_DISPATCHER_AGENT_SCRIPT", local_scripts)
        self.assertIn("last_sent_ip", local_scripts)
        self.assertIn("last_sent_at", local_scripts)
        self.assertIn("--endpoint-id", local_scripts)
        self.assertIn('"X-DDNS-Key": token', local_scripts)
        self.assertIn("def response_failure", local_scripts)
        self.assertIn("PreserveMethodRedirectHandler", local_scripts)
        self.assertIn("NetworkManager", local_commands)
        self.assertIn("DOCKER_INFRA_DDNS_PUBLIC_IP_URLS", runtime_config)
        self.assertIn("DOCKER_INFRA_PUBLIC_IPV4", runtime_config)
        self.assertIn("def public_dns_address", runtime_config)
        self.assertIn("ddns.dispatcher.ensure", runtime_config)
        self.assertIn("_service_public_dns_content", domains)
        self.assertIn("config.public_dns_address", nginx)
        self.assertNotIn("content=config.advertise_address(env)", nginx)
        self.assertNotIn("_split_domains", nginx)
        self.assertIn("ddns_model.register_service_domains", nginx)
        self.assertIn("ddns_managed", nginx)
        self.assertIn("DDNS 관리 서버 등록", preflight)

    def test_search_select_applies_selection_on_first_click(self):
        template = SEARCH_SELECT_TEMPLATE.read_text(encoding="utf-8")
        view = SEARCH_SELECT_VIEW.read_text(encoding="utf-8")

        self.assertIn('(mousedown)="selectItem(item, $event)"', template)
        self.assertIn('(click)="stopEvent($event, true)"', template)
        self.assertIn('(keydown.enter)="selectItem(item, $event)"', template)
        self.assertIn("stopImmediatePropagation", view)
        self.assertIn("@Input() value: any = ''", view)
        self.assertIn("this.value = this.itemValue(item)", view)
        self.assertIn("this.valueChange.emit(this.value)", view)
        self.assertIn("this.cdr.detectChanges()", view)


if __name__ == "__main__":
    unittest.main()
